### ISSUE TITLE
Automate version number

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#110]
Current the version number is hard coded in the opsdroid/const.py file which causes problems if it is accidentally not updated as in v0.7.0.

This should be set automatically at runtime either from the previous production build or from the current working repository.

**Comment by go8ose** [comment]
Hi @FabioRosado. I was looking at your commits. Doesn't referencing pypi like this mean that when there is a new release on pypi all the existing opsdroid installations would incorrectly start reporting they are the new release?

**Comment by FabioRosado** [comment]
@go8ose  Yeah that's correct and that's the reason why we didn't use the PR  👍

**Comment by go8ose** [comment]
Having a single authoritative location for the version number, which is tracked in revision control, sounds like a good idea to me.  I don't understand what the problem is.

Is there a documented procedure for doing a release, and does it mention that you need to do a commit that increments the version number (maybe post release, so the version number in master is always the next releases version)?  Or alternatively, can you describe what happened with v0.7.0 that caused this issue to be raised?

(I wasn't looking at this project back in February when 0.7.0 was done, so I might be missing some context).

**Comment by jacobtomlinson** [comment]
@go8ose yes I agree that a documented process would be useful. 

The issue in February was me forgetting to update the `const.py` file before doing a release, which having a documented process could've avoided.

One thing that could be even better would be to automate the release process, something akin to running `make release <version>`. This could update the `const.py` file, generate the release notes and create the release on GitHub.

**Comment by go8ose** [comment]
@jacobtomlinson I had a look at how to pass a parameter to a make file.  According to https://stackoverflow.com/questions/2214575/passing-arguments-to-make-run you can arrange for your make file to allow:

> make version=1.0.0 release

According to https://stackoverflow.com/questions/2826029/passing-additional-variables-from-command-line-to-make you could also do:

> make release version=1.0.0

I imagine the make file would simply pass that parameter to a python script. I wonder if you really need to involve the make file.  Would you be open to a PR that starts scripts/do-release, which is a python script that you just call directly?  Perhaps the PR would also start a docs/project/making-a-release.md document that describes the process for doing a release?

**Comment by jacobtomlinson** [comment]
@go8ose I personally like using make, however I can understand that it does add another level of abstraction.

For now let's just go for documenting the process as I'm the only one following it for the time being. As the project grows it may be useful to automate the process.
