### ISSUE TITLE
Codecov not reporting

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#1101]
For some reason coverage reports are never happening on new PRs.

**Comment by FabioRosado** [comment]
I've been trying to fix this the whole morning but can't figure out why codecov is not reporting. I've even tried to check the verbose log to see if there was any issues with it - on the forums someone had a problem because the file was too big - but codecov sends the report to the s3 bucket and the coverage report is working fine.

For some reason the issue seems to be trying to push the coverage report back to github. I'm not sure what do to in regards to this 🤔

**Comment by jacobtomlinson** [comment]
Might be related to [this issue on their end](https://status.codecov.io/incidents/m1gbpnq16kqv) from yesterday.
