### ISSUE TITLE
Improve Config Schema Validation

### ISSUE THREAD

**Issue by Cadair** [opsdroid/opsdroid#1186]
Currently when the schema fails to validate it gives a very unhelpful error, i.e.:
```
Error validating data /home/polesz/.config/opsdroid/configuration.yaml with schema /home/polesz/Projects/python/devbot/.venv/src/opsdroid/opsdroid/configuration/schema.yaml
	connectors.1.name: 'matrix' is not a regex match.
	connectors.1.name: 'matrix' is not a regex match.
	connectors.1.name: 'matrix' is not a regex match.
	connectors.1.webhook-url: Required field missing
	connectors.1.access-token: Required field missing
	connectors.1.name: 'matrix' is not a regex match.
	connectors.1.verify-token: Required field missing
	connectors.1.page-access-token: Required field missing
	connectors.1.name: 'matrix' is not a regex match.
	connectors.1.rooms.main: Required field missing
	connectors.1.name: 'matrix' is not a regex match.
	connectors.1.api-token: Required field missing
	connectors.1.name: 'matrix' is not a regex match.
	connectors.1.token: Required field missing
	connectors.1.name: 'matrix' is not a regex match.
	connectors.1.consumer_key: Required field missing
	connectors.1.consumer_secret: Required field missing
	connectors.1.oauth_token: Required field missing
	connectors.1.oauth_token_secret: Required field missing
	connectors.1.name: 'matrix' is not a regex match.
	connectors.1.room-id: Required field missing
	connectors.1.access-token: Required field missing
```
the actual issue here was there was no `'main'` in the `rooms` dict, not that you would ever know it from that error :stuck_out_tongue_closed_eyes: 

I don't know if this is a limitation of the validation library (I also can't think of another one which gives reliable errors), but I think this is actually making the user experience of misconfiguring opsdroid worse (as demonstrated by #1159 etc).

**Comment by Cadair** [comment]
see also #1188

**Comment by jacobtomlinson** [comment]
Yeah this isn't great. There have been a bunch of issues since we added the schema validation.

Unless we can get more sensible error messages from the validation I propose that we disable it for now and re-open the issue to implement it. The current implementation doesn't seem to be fit for purpose.

**Comment by FabioRosado** [comment]
I've been playing around with validators and heres what I think:

**Cerberus**
The schema seems overcomplicated imo:

```python
schema = {'logging': {'type': 'dict', 'schema': {'level': {"type":"string"}, 'console': {'type':'bool'}}},
'welcome-message': {'type': 'boolean'}, 
"parsers": {"type": "list", "schema": {"type": 'dict'}, 'schema': {'name': {'type': "string"}, 'access-token': {'type':'string', 'empty': True}, "min-score": {'type': "integer"}}},
'connectors': {'type': 'list', 'schema': {'type': "dict", 'schema': {"name": {'type': 'string'}, 'token': {'type': 'string', 'required': True}}}},
'skills': {'type': 'list', 'schema': {'type': "dict", 'schema': {"name": {'type': 'string'}}}}}
```

error shows as: 

```python
cerberus.schema.SchemaError: 
{'logging': [{'schema': ['no definitions validate', {'anyof definition 0': [{'console': [{'type': ['Unsupported types: bool']}]}], 'anyof definition 1': [{'console': ['unknown rule'], 'level': ['unknown rule']}]}]}], 'welcome-message': [{'type': ['Unsupported types: bool']}]}
```

At the moment I'm getting a `TypeError: argument of type 'bool' is not iterable` that seems to be coming from cerberus.schemas

**Voluptous**

The schema seems to be as close as the config and easy to write:

```python
 schema_test = {
'logging': {'level': str, 'console': bool}, 
'welcome-message': bool, 
'parsers': [{'name': str, 'gateway': str, 'assistant-id': str}],
'connectors': [{'name': str, 'token': str, 'access-token': str}], 
'skills': [{'name': str,}], 'databases': [{'name': str}]}
```

The error handling seems easy to understand but there is one thing that I don't like - it will only throw up the first error, so if you have multiple issues on your config it will take x amount of runs until you can finally run opsdroid.

The thing I like here is that you don't need to write every single thing in the schema. Let's say you got a connector that has `token` and others that uses `access-token` then you can just write both in the schema and it will be validated accordingly.

```python
voluptuous.error.MultipleInvalid: 
expected bool for dictionary value @ data['logging']['level']
```

_Note: I've used a messed up schema to check the errors._

I tried jsonschema but I don't seem to be able to validate the parsers since its a list containing dictionaries. The schema format looks much like cerberus one.

I've also had a look at schematics but seems that using a class base for the schema will just add too much complexity and I'm not sure how it would react to our nested structure.

Perhaps the best option would be to replace yamale with voluptuous? The reason for me saying this is that it's unlikely that a user will have a lot of things wrong on the configuration - maybe one or two items.

If we choose to replace yamale I'd also suggest we should look into the whole `load_config_file` method and perhaps turn this into a function of its own in a separate file since the method is pretty big 🤔 


What do you think of all this?

**Comment by Cadair** [comment]
:+1: for Voluptous I have used it before and it's pretty nice to work with.

**Comment by jacobtomlinson** [comment]
Agreed Voluptuous is good and well used.

**Comment by Cadair** [comment]
>  then you can just write both in the schema and it will be validated accordingly.

I am pretty sure you can turn this off where you need to.

**Comment by FabioRosado** [comment]
Since #1212 added voluptuous and improved the schema I am going to close this issue 👍
