### ISSUE TITLE
Web configurator

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#124]
Maybe opsdroid should be able to be configured using a web UI instead of hacking yaml directly.

**Comment by jacobtomlinson** [comment]
This could be handled through the API to allow modification from [opsdroid-desktop](github.com/opsdroid/opsdroid-desktop)

**Comment by jacobtomlinson** [comment]
It's been nearly a year since I raised this issue and I wonder if now some of the community members have thoughts?

Are you happy configuring opsdroid via a `yaml` file, or would you prefer to configure it through some GUI? We could aim for a hybrid approach but that would likely end up in the yaml being rewritten when you update through the GUI and things like comments would be lost.

cc @FabioRosado @anxodio @go8ose

**Comment by redfruitt** [comment]
I'm not sure a GUI would provide the same level of flexibility we get from the yaml file.

**Comment by jacobtomlinson** [comment]
@redfruitt thanks for your thoughts! What makes you say that?

**Comment by redfruitt** [comment]
So the configurational file seems to be more intuitive (for me atleast) to look into while trying to add
new skills/connections/parsers. For example if I'm trying to add new connector, I can always glance at the defined example or existing connector above and write up the necessary parameters for it.

Also adding and removing a component is as simple as commenting/uncommenting. If we introduce a GUI, we could be taking away the intuitiveness of the current setup.

**Comment by jacobtomlinson** [comment]
Thanks that's useful information!

**Comment by FabioRosado** [comment]
I haven't thought much about this yet to be honest, but perhaps it could be possible to add a sort of "settings" option to opsdroid-desktop in which a page - layout opens and you can add the configuration through a sort of GUI? 

Not sure if that makes sense, apologies if it doesn't been up since 4 am haha

**Comment by anxodio** [comment]
I think that remove the yaml it's a bad idea, because it's harder to copy and move the configuration (dev/prod), and deveopers or administrators are normally used to work with this kind of file configuration (yaml/json/ini...).

It could be nice have a helper GUI that, as @jacobtomlinson said, rewrites the yaml. It can help to non technical users to setup an opsdroid demo in an easy way. But it has some troughs like comment removing and reformatting.

So my point is that yaml configuration must exist, and we can simply add a helper GUI. But I think that the ROI of this GUI at the moment will be very low.

**Comment by jacobtomlinson** [comment]
Thanks for the feedback everyone! I'm going to close this off for now but it can always be revisited at a later date.
