### ISSUE TITLE
Only run one skill per message

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#154]
Currently all matching skills will be executed when a message is parsed. This will add complications when dealing with context. Therefore it would be better to just run one skill.

Requires #155

**Comment by go8ose** [comment]
How will ties be broken? If #155 is implemented it's conceivable that two matches will both have rank 1.0 (or 100%, however the ranking system works).  Perhaps core would respond with a message saying this is an error condition, and the configuration and logs should be checked, then not run any skill.

**Comment by jacobtomlinson** [comment]
That's definitely an interesting question. I don't think resulting in an error is necessarily the best way to handle this. But I can't immediately think of an alternative.

**Comment by gabeduke** [comment]
You could give a choice which skill to run

**Comment by go8ose** [comment]
How do you give a choice?  Do you mean you have a third skill, an "arbitrator" skill that only sends messages in this situation, and asks the user how to proceed?  That sounds a bit awkward.

Maybe it should log an error message, and run all the matching skills.  Or maybe there should be a configuration option that picks between run all matches, run 0 matches, or run a random match

… actually, let's not provide a random option.  That sounds like a terrible idea.

**Comment by gabeduke** [comment]
It's not the users fault that 2 skills recognize the same language. I feel like they should still be able to complete their request. The issue is that if it errors out they won't be able to use the skill unless they remove  the conflicting one. if they decide to keep both the bot could let them choose which path to follow.

**Comment by go8ose** [comment]
@gabeduke I agree with you that it's not the users fault.  I just think it might be hard to implement.  What happens if opsdroid sends a reply to the user, and their answer comes back and two matches match this later message?  That's why I proposed a deterministic action driven by the configuration.  If there is also an alert sent to the user, the user can try and ask the administrator of the bot to do something about the situation (maybe altering a weighting that is given to a matcher).

**Comment by jacobtomlinson** [comment]
I've had a go at implementing this in #311. 

The way ties are broken are by creating a list of skills which match and giving them a score, then I use the `sorted` method to order them and select the 0th element from the list. This does lead to a rather arbitrary tie breaker which is akin to randomly selecting one.

I agree with @go8ose that this is not ideal and it would be great for the user to feed back on this. I also agree with @gabeduke that the bot should complete some kind of action.

I'm also hopeful that the confidence scores returned by the NLU apis have enough significant figures that this is a very rare occurrence.

I would appreciate further feedback.
