### ISSUE TITLE
Tests should be excluded from coverage

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#1563]
As we are moving tests into the opsdroid directory they are now tested for coverage. 

This doesn't always make sense, for example when asserting something doesn't raise we want to catch an exception and fail the test. So for a passing year suite the except block should not be run. 

We need to update the coverage config to exclude all `tests` directories within `opsdroid`.

**Comment by Waterbyte** [comment]
@jacobtomlinson I think the two files that decide coverage configurations are .coveragec and codecov.yml. I did some research and placed **\*/tests/\*** in both the files under omit section. I chose to put forward slash before and after **tests** so that wildcard don't confuses it with directory names like _fastests_ or something like _gatestses_. I hope this is OK or does it need some edits?

**Comment by jacobtomlinson** [comment]
Perfect many thanks!
