### ISSUE TITLE
Feature request: Please consider implementing a 'catch-all' responder

### ISSUE THREAD

**Issue by law** [opsdroid/opsdroid#1610]
# Description
I have a skill with many regex matchers, all starting with some flavor of "botname".  ex: 
```
botname get environment
botname get hostinfo
botname get verbose hostinfo
botname get hosthealth
botname get verbose hosthealth
```

etc, with various complexities of regex applied to capture hostnames, etc.  It would be nice to be able to define a 'catchall' matcher that would fire only if it was the only string matched.  For example, if a user typed the invalid string: 
```
botname gte infohost
``` 
that would match nothing in the above list.  If there was a 'catchall' that was set to match strings for "^botname", it could fire a "print help text" message so long as the string didn't match any of the other responders.  

## Versions
- **Opsdroid version:** 0.19.0
- **Python version:** 3.8.4
- **OS/Docker version:**

## Configuration File
n/a

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

**Comment by jacobtomlinson** [comment]
This is an example of opsdroid being treated like a command line in your chat client. 

Many design decisions in opsdroid were based on moving away from this use case to something more natural where the bot would be in a room with many other people and it would robustly respond to queries like "what is the environment?", "can you tell me the environment?", "please get environment", etc. These kind of requests would be mixed with other chat between colleagues which is not aimed at the bot.

One thing that use case didn't consider is someone directly addressing the bot but asking something the bot doesn't understand. For example "botname please get the flargle bargle". In that case the bot is being addressed directly and so it should respond, but the question doesn't match anything.

In #273 we discuss the bot being able to know when it is being spoken to. This would open us up to being able to catch that situation.

Given that many folks seem to use opsdroid as a CLI in chat, rather than a natural language bot, I think it would be reasonable to add a catchall matcher. But we should be thoughtful about users who do have bots in rooms with other conversations going on.

My initial design would be something like this.

```python
class MySkill(Skill):

    @match_catchall
    async def catchall(self, event):
        await event.respond("Sorry I have no idea what you are talking about")
```

The catchall logic would probably go somewhere like `get_ranked_skills`. If the `ranked_skills` list was still empty at the end of the function we would check for the catchall matcher and return that. This does assume only one use of `match_catchall`.

https://github.com/opsdroid/opsdroid/blob/c2792eab5196e2cbbd4f62d1c8e9e70db36d3e36/opsdroid/core.py#L436

This would then support the design from #273 (which would probably be implemented as a constraint in modern opsdroid) where we could do something like this.

```python
class MySkill(Skill):

    @match_catchall
    @constrain_spoken_to
    async def catchall(self, event):
        await event.respond("I think you were talking to me, but I have no idea what you're asking")
```

That way the catchall matcher would only trigger if the bot is addressed directly.
