### ISSUE TITLE
The case for multitenancy

### ISSUE THREAD

**Issue by ajitdsa** [opsdroid/opsdroid#1807]
# Description
This is meant to be more of a good spirited discussion than an "issue". Please consider it as such.

Let's say you create an opsdroid with a certain set of skills, and now you would like multiple groups/organizations/customers/whatever to use these skills. It feels like currently the way to do this would be to set up an opsdroid _PER_ group/organization/customer/whatever. I say this because of the configuration file. Each `connector` in this file is able to have 1 token or credential set or whatever in that file.

What I would like to propose/brainstorm is a way that we could achieve multitenancy with opsdroid so that we can install one opsdroid instance and then use that to respond to requests from multiple organizations using the same skills. I am actively working on a POC for this using the Github connector (because that is my current use case) but I fear this is a short-sighted approach and that if the group thinks multitenancy could be an interesting thing, then it should be more on a full opsdroid level.

Anyways, just wanted to open this topic for discussion.

## Declaration

I want to admit that I am likely the "corporate shill" here, and I understand that I may be advocating for things that more corporate users of opsdroid would like rather than a typical use case. But I'm also attempting to get my company to be a supporter of OSS in general, and I'm using much of my experience with this project as the launchpad. However, I would like to be respectful of this project's intentions while I advocate for new things. So I'm hoping that taking both viewpoints into consideration is possible. Thank you.

**Comment by jacobtomlinson** [comment]
Hearing about new use cases is great, I'm excited to learn more about what you are trying to build.

In my mind, I can see two scenarios where multi-tenancy is desirable. If there are more scenarios that I am not thinking of it would be great to hear about them.

**Scenario A: Building a public GitHub app**

You are trying to build something like [stale bot](https://github.com/apps/stale) where you build one app which is available in the GitHub marketplace that many folks install and use. 

As an example you could write a bot to comment on and eventually close inactive issues/PRs.

Example workflow:
- Connect to GitHub with App auth
- Create a crontab matcher skill
  - The skill would list all repos that the app is installed on
  - For each repo it would check all open issues and PRs against stale criteria
  - It would comment/close as appropriate

Required changes:
- Add support for [authenticating as an App](https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps#authenticating-as-a-github-app) instead of with a personal access token
- Add some helpers for [listing installations of the app](https://docs.github.com/en/rest/reference/apps#list-repositories-accessible-to-the-app-installation)


**Sceneario B: Connect one opsdroid to multiple bot accounts**

Today you must create a new GitHub user and generate a personal access token. Opsdroid then can control that account.

It may be desirable to create many of these accounts and have a single opsdroid instance control them all with the same set of skills. 

As an example you could write a bot which comments on all newly opened PRs thanking the user for their contribution and letting them know someone will review it soon.

Example workflow:
- Connect to GitHub with personal access token A
- Connect to GitHub with personal access token B
- Connect to GitHub with personal access token C
- Create a skill that matches the PR creation event
  - The skill would respond to the PR

This workflow would work today, you just need to configure multiple instances of the GitHub connector.

```yaml

connectors:
  github-foo:
    token: aaabbbcccdddeee111222333444
    secret: <webhook secret>
    module: opsdroid.connector.github

  github-bar:
    token: aaabbbcccdddeee111222333444
    secret: <webhook secret>
    module: opsdroid.connector.github

  github-baz:
    token: aaabbbcccdddeee111222333444
    secret: <webhook secret>
    module: opsdroid.connector.github
```

---

My two main worries about both for these approaches are:
- As more folks install opsdroid it would eventually reach a scaling limit. Today Opsdroid is not designed to work in a clustered or high availability setup.
- If you are operating opsdroid on the behalf of many customers then you could potentially be mixing various private info from different customers in the opsdroid memory. I guess it would be the skill author's responsibility to ensure that each customer is isolated and that there is no leakage between customers. In #1806 we are discussing one database table per skill, perhaps it should be one database table per connector per skill.

None of this is a showstopper, just something to be mindful of.

@ajitdsa does this align with what you have in mind? Am I missing anything? Are there other scenarios or desires here?

**Comment by jacobtomlinson** [comment]
> I want to admit that I am likely the "corporate shill" here

Corporate shills are very welcome here 😆. If you have time to contribute features and maintain them going forward then we are happy to add features that are more enterprise focussed. Just as long as we still support the current community of more DIY bot builders.

**Comment by ajitdsa** [comment]
Oh wow, great answer. Thanks so much, @jacobtomlinson.

So I wasn't aware that your *Scenario B* outlined above already works. I'll see if I can give it a try and make a documentation PR about this for you. Nice.

**Use Case:**  What I was talking about was more akin to *Scenario A*. We would like for customers of our product to be able to install a Github app. For us specifically, the idea is that we send information from Github automatically to an API in our kanban project management software. Then we could also get information back from that API to respond as a new comment in Github. thus adding much needed context bidirectionally. (We will also likely add some more Github interactions to support this, but that's a separate and likely simpler issue.) But we'd like to enable this functionality for any customer who uses our software and installs the Github app.

In the future, we might want to attempt to enable these same Github triggers to create messages in Slack. Not an immediate concern, but just food for thought and something I'll be thinking about.

> If you have time to contribute features and maintain them going forward then we are happy to add features that are more enterprise focussed. Just as long as we still support the current community of more DIY bot builders.

Absolutely.

**Comment by jacobtomlinson** [comment]
Awesome. I am very keen that we work on the requirements to make scenario A a reality.

I propose that we close this issue out and open up a new one to cover app style oath in the GitHub connector. Do you think you could raise that?

**Comment by ajitdsa** [comment]
Yes, absolutely. This is great. Thanks @jacobtomlinson!
