### ISSUE TITLE
Upgrade redis database backend to use aioredis v2

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#1810]
Looks like v2 of `aioredis` is out and has breaking changes which affect us. In #1809 I've pinned us to v1 for now but we should upgrade things to work with v2.

Specifically importing the parser fails

https://github.com/opsdroid/opsdroid/blob/a45490d1bdceca39b49880e20262b55ea0be101d/opsdroid/database/redis/__init__.py#L6

```python-traceback
   ImportError while importing test module '/home/runner/work/opsdroid/opsdroid/opsdroid/database/redis/tests/test_redis.py'.
  Hint: make sure your test modules/packages have valid Python names.
  Traceback:
  /opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/importlib/__init__.py:127: in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
  opsdroid/database/redis/tests/test_redis.py:8: in <module>
      from opsdroid.database.redis import RedisDatabase
  opsdroid/database/redis/__init__.py:6: in <module>
      from aioredis import parser
  E   ImportError: cannot import name 'parser' from 'aioredis' (/home/runner/work/opsdroid/opsdroid/.tox/py37-e2e/lib/python3.7/site-packages/aioredis/__init__.py)
```

**Comment by MrNaif2018** [comment]
Hello! I would like to take it up. Hacktoberfest is coming and it's becoming my good tradition to visit opsdroid and help a bit (: 
One question before starting:
https://github.com/opsdroid/opsdroid/blob/a45490d1bdceca39b49880e20262b55ea0be101d/opsdroid/database/redis/__init__.py#L49-L54
Is the pure python parser setting intentional (it is slower)? Aioredis 2.0 uses hiredis parser if hiredis is installed, pure-python fallback otherwise
