### ISSUE TITLE
Add test execution for Docker in Travis config file

### ISSUE THREAD

**Issue by gtseres** [opsdroid/opsdroid#234]
There were a couple of issues that came up when running opsdroid in a container ( #232  , #219 ), so it would be a good idea to add some Docker related testing into the `.travis.yml` file. This way, we can make sure that the unit tests are executed in the container offering of opsdroid as well.

**Comment by gtseres** [comment]
I can look into this, please let me know if any suggestions / concerns.

**Comment by vitkhab** [comment]
I've added basic test in my PR for building and running container. It doesn't check for being in working state (it's much more work with mocking and etc. as I see it). But it should be good for start.

Still have a questions.
- Now it use no config. Should be one there? For testing only purposes?
- I see an error in container logs https://travis-ci.org/vitkhab/opsdroid/jobs/295272026#L668 . Should I parse logs and fail build if there are errors? Or should I presume if it's running - it's working?

**Comment by jacobtomlinson** [comment]
Thanks for making a start on this! I had a read of the blog post you shared, it's quite interesting.

To answer your questions:
- When you specify no config it uses the default config, which should be fine.
- That error is raised in #219 and requires further investigation.

I have some thoughts. Currently the travis tests are separated into three separate builds, `py35`, `py36` and `lint`. Your PR adds docker testing to all of these environments, so the container gets tested three times in every build. I think it would be better to add a fourth environment (called `docker`) and only do the docker testing there. That means removing the docker build and run commands from the `.travis.yml` file and adding them to the `tox.ini`. 

It also may be better to run `py.test` within the container rather than opsdroid itself as we are currently not doing end-to-end testing via travis. This may be something we want to add in the future, but lets be consistent for now.

**Comment by vitkhab** [comment]
I tried to make test configuration and poll API with curl from outside container and I had an idea.
I think it will be better to add `HEALTHCHECK` command inside dockerfile (with `curl localhost:8080`) and then poll container status in tox. So it will be the consistent place to look for health status of container in tests and in production. How does it sound?

I see no pros or cons in running tests inside a container. It will be ok if the main distribution of opsdroid is container. If it is distributed as python module or there are plans to do so, I see no point in testing inside container. Please explain a problem you are trying to solve with running tests inside.

**Comment by jacobtomlinson** [comment]
I see where you're coming from. I agree the healthcheck could be good in the future.

My concern is mixing unit tests and end-to-end tests. I'm happy to have both eventually but the scope of this issue is to check that the unit tests run in the container.

It's not a question of whether docker will be the main distribution instead of the python module. Both are important and supported distributions. 

Running the tests inside the container will show whether the dependencies have been installed correctly and that the units are in a functioning state.

**Comment by vitkhab** [comment]
Thank you. I've understood the needs and I'll start working on it right away
