### ISSUE TITLE
context matcher

### ISSUE THREAD

**Issue by go8ose** [opsdroid/opsdroid#269]
I wonder if a "context" matcher might be a good idea, to limit skills to specific rooms, or users. Example:

```python
config = ... #get the opsdroid config somehow
@match_context(connector=config.skill.manage_vms.connector, room=config.skill.manage_vms.channel)
@match_regex(r'delete VM (.*)')
async def delete_vms(opsdroid, config, message):
  vm = message.regex.group(1)
  result =  await delete_the_vm(vm)
  await message.respond('Result of deleting VM {}: {}'.format(vm, result))
```

Now that I've written that out, getting the config outside of the skill looks clumsy.  Perhaps the skill should just check it's configuration, connection, room (etc) when it's running.  What do other people think?

**Comment by jacobtomlinson** [comment]
That's a really interesting way to think about it. There is an issue (#156) discussing this however I do like the idea of having an additional decorator instead of kwargs in the existing decorators.

You're right about getting access to config items. This has crossed my mind before as it would be interesting to allow overriding regex items in the config which would also require access to the config outside of the method.

Perhaps a way around this would be changing skills to be methods of a class instead of a bunch of standalone functions. Not sure.

**Comment by jacobtomlinson** [comment]
Moved your question to #156 and copied my response their. Closing in favour of that issue.
