### ISSUE TITLE
Add recast.ai matcher/parser

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#337]
# Description
Add a matcher and parser to use the [recast.ai API](https://man.recast.ai/#analyse-endpoints
).

**Comment by FabioRosado** [comment]
I've played around with this a bit and got a question for you @jacobtomlinson, should we use only the NPL Api endpoint? Because recast.ai offers a dialog function, but due to the nature of opsdroid I'm not sure if there is any point implementing it.

Also, recast.ai has their own python package to interact with the api. At the moment I'm not using it to avoid importing another module. Should I keep  interact with the api with aiohttp?

Thank you
