### ISSUE TITLE
Improve 'adding skill' documentation

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#377]
# Description

Looking at the Google Analytics from the documentation it shows that many users visit the root of the documentation and then immediately navigate to the "adding skills" page. This page could be improved as it makes assumptions that the user has read the getting started page.

http://opsdroid.readthedocs.io/en/latest/extending/skills/

The page immediately jumps in with things like:

> To create a skill you need to create a single python file in your repository with the __init__.py name. For example the skill hello has a single file called __init__.py.

But it doesn't answer things like "what repository?", "how do I create that?", "how do I configure opsdroid to find it?". 

Perhaps there should be a first paragraph explaining how to create a skill repo, how to configure opsdroid to load it and then move on to actually writing the skill.

**Comment by anujgtm1** [comment]
Hi @jacobtomlinson, I'd like to contribute to the project starting with this issue. I'm a newbie and this would be my first open-source contribution. What documents would you recommend reading regarding contribution to the project? and what should I give special attention for this issue?

**Comment by FabioRosado** [comment]
Hello @anujgtm1  and welcome!

I'd recommend you read the [tutorial series](http://opsdroid.readthedocs.io/en/latest/tutorials/introduction/) first just so you know how opsdroid works. But if you have been playing around with opsdroid you probably know how to create a skill already.

The documentation about [opsdroid configuratio (http://opsdroid.readthedocs.io/en/latest/configuration-reference/) has some useful information there as well.

Things you can include in adding skill documentation:
- Explain how opsdroid finds the skills (from a repo or a folder)
- Explain how you can set a path (from repo/folder) in config.yaml
- a link to the tutorial
- anything else you think it should be added because is not too clear

Let me know if you need any help 👍
