### ISSUE TITLE
Dependency hell: opsdroid needs aiohttp 3.3.2 and slacker-asyncio needs 3.0.2

### ISSUE THREAD

**Issue by Cadair** [opsdroid/opsdroid#558]
I just removed slacker-asyncio from requirements.txt and it worked. :confused:

**Comment by FabioRosado** [comment]
Slack is now merged into the core of opsdroid, by removing slacker-asyncio it didn't break opsdroid for you?

**Comment by Cadair** [comment]
It didn't seem to. 

Why did slack get merged into core ooi?

**Comment by FabioRosado** [comment]
Due to issue #185 Jacob worked and merged slack and websocket into the core, other connectors will eventually be merged as well. Opsdroid didn't drop the connector class though so users can still create their own connectors

**Comment by jacobtomlinson** [comment]
We should probably update the connectors to use a more flexible requirements file rather than pinning the version. However as @FabioRosado said this should be relevant to Slack as of the next release due to it being merged into the core.

**Comment by FabioRosado** [comment]
I was looking at the [skill words](https://github.com/opsdroid/skill-words) and it contains a requirement.txt file, I didn't mention anywhere that you should install the requirements manually, does opsdroid get the dependencies of the file if it's in the folder?

I'm only asking because if opsdroid does that then perhaps we could extend the functionality to connectors as well (if it's not in place yet)

**Comment by jacobtomlinson** [comment]
When you configure the skill opsdroid will install the requirements file as part of installing the skill. Same for connectors and databases. Those dependencies get installed into a separate `site-packages` directory which is added to the path dynamically when the skills are loaded.

**Comment by tdavis** [comment]
I ran into this earlier too. It happens if you use opscode from source to get the included connectors. I ultimately had to just back out to the pypi version and copy-paste the source for the connector I wanted to modify. The entire process of which is quite obscure. I had to read the source code to find out that if I added a `path` key to the yaml pointing to my connector it would stop trying to install it from Github. I would have liked to simply extend the opsdroid connector, but that _isn't_ published to pypi and has no `setup.py` so no dice there.

More generally, the whole module loading thing is very foreign to me as a Python developer. Why can't I install a skill or connector with `pip` (or work on one locally with the convenient `python setup.py develop`), point to the class in the yaml like `foo.bar.Baz`, and opsdroid can just `import()` it? I'm sure there's a reason for rolling your own module loading stuff, but using it to make opsdroid load my own code is not intuitive. 

In any case, thanks for your work on the project!

**Comment by jacobtomlinson** [comment]
Thanks for commenting @tdavis, you make some interesting points.

> The entire process of which is quite obscure.

I totally take your point here. In the initial design for opsdroid I was striving to avoid the way hubot handles it's packages. In that project you npm install your skills/connectors and they magically appear because hubot imports all packages named `hubot-*`. However I kept running into issues where bugs in the connectors were hard to trace back and the fix was often to remove the package, roll a custom one and install it. This was one of the many reasons why I abandoned hubot and started opsdroid. I wanted everything in opsdroid to be declarative in the config file so things can be easily enabled/disabled. 

I also aimed the project at sysadmin/ops folks who in my experience write a lot of python but as more of a scripting language. They generally have a shallow knowledge of package management and module creation. I wanted to allow people to write skills as a simple python script which they point to in the config, hence all the custom loading stuff. With the whole devops movement this is changing, so perhaps opsdroid needs to change too. However I want to avoid the flow being "write a custom python package, install it, then reference it in your config" as this is a steeper learning curve than I'm aiming for.

> I had to read the source code to find out that...

There is [documentation for this](http://opsdroid.readthedocs.io/en/stable/configuration-reference/#module-options). However the fact that you resorted to reading the code means it is not easily discoverable. I would be really keen to get some documentation fixes from anyone who has struggled to find things in the docs.

> More generally, the whole module loading thing is very foreign to me as a Python developer.

I feel like you are more advanced in python development than audience I had in mind when I designed opsdroid. However that is certainly an oversight on my part. I'm very open to make opsdroid comply with general python development practices.

> Why can't I install a skill or connector with pip ... [and] point to the class in the yaml like `foo.bar.Baz`

This is a really nice idea! I totally see the appeal of this kind of approach. Would you mind raising a separate issue feature request to implement this?

**Comment by jacobtomlinson** [comment]
#587 downgrades aiohttp for now.

**Comment by jacobtomlinson** [comment]
#588 has been raised by @pyup-bot to put it back up again. We can discuss long term fixes there.

**Comment by Cadair** [comment]
So I just wanted to put a quick note in here, with another side effect of this I encountered today. I have a skill that was using the synchronous version of slacker, which now does not work with opsdroid v0.12. (Annoyingly it also needs features introduced after 0.11). This seems to be for some *inexplicable* reason `slacker-asyncio` is also provides the `slacker` package.

The way out for me again, was just to `pip uninstall slacker-asyncio`, because I just don't need the slack connector (yet). I really don't want to complain too much, I really like opsdroid and it has made many projects of mine very easy. I just want to point out that merging the slack connector into core has only caused me problems.

**Comment by jacobtomlinson** [comment]
@Cadair sorry that this has caused you so many problems.

As far as I'm aware `slacker-asyncio` takes the regular `slacker` package and overrides the methods which call the Slack API with async coroutines. Hence it needing to install the `slacker` package. 

I'm currently exploring setting up more flexible dependencies for opsdroid as I'm aware they are far too rigid.

One additional option would be to make connector specific dependencies optional.  What do you think?

Also would you mind raising another issue detailing the exact issue you're having?

**Comment by Cadair** [comment]
I didn't open a new issue, because it's not really an opsdroid bug, it's really an issue with `slacker-asyncio`. In that if you install `slacker-asyncio` then `import slacker` you get `slacker-asyncio` and not `slacker`, which means that you can't use the async and non-async version of slacker at the same time (I think). (I also think I have found some actual bugs in `slacker-asyncio` as well).

I think making the connector dependencies optional in theory is a good idea, but as @tdavis has already commented the opsdroid dependency handling can be a little unintuitive to people familiar with Python, so I would not just want to suggest it's a magic solution.

**Comment by FabioRosado** [comment]
Slacker-asyncio is currently having some issues with hard-coded version of aiohttp that's  one of the big issues with it. I hope that this will change soon, I have submitted a PR and opened an issue on the project page and will wait for a reply otherwise I will try to submit another PR in order to get slacker-asyncio to accept an aiohttp version > than 3.0.5 - hopefully this could help some of your issues @Cadair

**Comment by jacobtomlinson** [comment]
@Cadair I hadn't really noticed that that had overridden the naming. I wrote the connector a while ago. That is rather annoying and I see where you are getting frustrated. It looks like they have forked slacker and upgraded it to be async, rather than providing an async wrapper. 

Part of the idea of moving the connectors and databases into the core is to try and get away from the custom dependency handling if possible. I still want to keep skills as simple as possible and that may mean having custom loaders, but as chat connectors and database modules are likely to be written by python developers it makes more sense to have them follow the regular workflows.

As for making slack optional I was thinking of using the regular setup tools and either doing:

```
pip install opsdroid 
pip install opsdroid[slack]
```

where the first command would install opsdroid core, and if you try to use the slack connector you will get an error saying that you need to install the optional slack dependencies too. Then the second installs those dependencies.

Or going for

```
pip install opsdroid[core]
pip install opsdroid [slack]

pip install opsdroid
```

Where the first installs just the core, the second installs the slack deps, and the third install everything.
