### ISSUE TITLE
Upgrade Dialogflow to V2 API

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#566]
There is now a V2 API for Dialogflow.

We should look at the parser and skill and upgrade the API if applicable.

https://dialogflow.com/docs/reference/v2-agent-setup

**Comment by FabioRosado** [comment]
I had a look at what changed on the V2 of the API and it seems a lot did change.  The major things that will need to be addressed are:

- Use OAuth instead of token to make api calls
- endpoint `/query` stops works and should know be `detectIntent` [documentation reference](https://cloud.google.com/dialogflow-enterprise/docs/reference/rest/v2beta1/projects.agent.sessions/detectIntent)
- webhooks are available now

The [migration reference](https://dialogflow.com/docs/reference/v1-v2-migration-guide-api) might be useful. We can use V1 of the API until 23rd of October 2019, so we should work on this in order to keep dialogflow working with opsdroid.

**Comment by jacobtomlinson** [comment]
Just had a reminder email that this needs to be done by October 23rd.

**Comment by FabioRosado** [comment]
I'll try to address this issue on my days off 👍

**Comment by FabioRosado** [comment]
I had a look at the documentation and started to try and wrap my head around the changes implemented to V2, it seems you need to use google cloud platform to authenticate your account, they also suggest that we should use the SDK in order to interact with dialogflow.

Should we write the dialogflow parser to use the sdk? 🤔
