### ISSUE TITLE
Should we use type hints?

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#639]
In opsdroid/connector-matrix#36 a [line](https://github.com/opsdroid/connector-matrix/pull/36#discussion-diff-216391788R19) containing [type hints](https://www.python.org/dev/peps/pep-0484/) has been proposed.

Given that these were a new feature in Python 3.5 and 3.5 is now the minimum supported version for opsdroid there is nothing stopping us from using them within the code base. For me this has raised a question about code style for this project. Until now I've always considered PEP8 to be the only set of formatting rules for opsdroid, and I'm keen to use any supported features of the Python language. For example when we eventually raise the minimum to 3.6 I will begin liberally sprinkling [f-strings](https://www.python.org/dev/peps/pep-0498/) throughout the code base because they are awesome.

The main reason that I feel differently about this is that type hints are an advanced feature of Python. One of opsdroid's goals is to be a safe place for beginner Python developers to cut their teeth in open source. Therefore I would like to keep the code simple, readable and beginner friendly. One of the things about Python that attracts beginners is the dynamic typing.

Given all of this I would love some feedback from the community on the following questions:
 - Would type hinting provide benefit to this project?
 - Is staying beginner friendly a strong enough reason to not use new language features?
 - Should we have a style guide for the project or is PEP8 enough?
 - Should we automatically allow all language features supported in our minimum Python version?

**Comment by FabioRosado** [comment]
I followed the discussion on [gitter](https://gitter.im/opsdroid/developers) and gave a bit of a thought about this issue. Unfortunately, my feelings are a bit mixed.

I agree with what has been said. Type hints do make functions look pretty ugly (I'm not a big fan of how it is implemented), it could be hard for new people to create functions with type hints.  In regards to google docstrings, not much changes with PEP 484 - you just more the type from the docstring to the line where you declare the function.

Now the reason why I'm mixed feelings about type hints, this is a new feature of the language and eventually, all functions will have type hinting - as everything, new features will eventually be adopted fully. So perhaps we should implement them either now or along the way (when they become more popular) - if this is the case we should just avoid doing double work and just implement them now.

Type hinting either in docstrings or function declaration will be beneficial to the project as it will improve understanding of the code simply because people will know exactly what the function expects and returns - this is something I struggled at times as I couldn't understand what was happening.

As for style guide, I think we should have one. That's one of the reasons why I wanted to implement Google docstrings throughout opsdroid, I've seen a few projects that use this style guide and it does make things easier when you are trying to understand the codebase and what does what. It also makes things much more tidy and that's good 😄

**Comment by drmorr0** [comment]
I have a few comments:

> The main reason that I feel differently about this is that type hints are an advanced feature of Python. [...] One of the things about Python that attracts beginners is the dynamic typing.

I don't know that I particularly agree with this statement.  Python isn't dynamically typed (well it depends what you mean by dynamically typed because even that term is overloaded to the point of being useless).  But for this discussion, every object in Python has a type and you can't (more or less) change that type.  It's just that the _source code_ never tells you what the type is, which leads to lots of hard-to-catch bugs.  My personal opinion is that using type annotations are a must-have best practice for Python developers to know about in 2018, and my experience is that they greatly improve the quality of a project.

> Would type hinting provide benefit to this project?

Yes, absolutely.  Combine the type hints with [mypy](https://mypy.readthedocs.io/en/latest/) and you have a really good extra bit of pre-run-time validation for your code (there are additionally some nice plugins for Vim that tell you as you're typing whether you've got your types correct or not).  Additionally, if you include type annotations in your project, then people who are developing skills or other extensions can make use of those annotations to ensure that their code is correct.

I've actually begun developing a set of type annotations in my project because I got tired of typing `message.response` instead of `message.respond` and not catching it until run-time.  If this proposal goes anywhere I'd be happy to contribute these upstream.

> Is staying beginner friendly a strong enough reason to not use new language features?

I think type annotations actually make the project more beginner-friendly.  It adds a bit of additional syntax that devs have to know, but it can catch a wide class of bugs that are often made by beginning developers.

>Type hinting either in docstrings [...]

If I get a vote, I'd say "please no typing in docstrings" -- that's mostly a backwards-compatibility thing for Python 2.7, and it makes certain things harder.

> So perhaps we should implement them either now or along the way (when they become more popular)

One of the nice things about type annotations and mypy is that it's not an "all-or-nothing" thing.  As you add more annotations, mypy is able to check and validate more things, but there's no requirement that you annotate everything in your code.

**Comment by jacobtomlinson** [comment]
Thanks for taking the time to write this 😀.

### Some responses

> Python isn't dynamically typed (well it depends what you mean by dynamically typed because even that term is overloaded to the point of being useless).

While you are technically correct I don't think it is helpful in this discussion. Python does not enforce typing in the same way as a strongly typed language. This makes things easier for beginners to get started, but also easier to tie themselves in knots. Type hints help avoid the type headaches of Python, but I feel it goes against a strong driving factor for people to use Python. If someone really cares about these principles then they should probably be using a different language. 

> My personal opinion is that using type annotations are a must-have best practice for Python developers to know about in 2018

While I agree with this I'm not sure it is going to be friendly to beginners.

> I think type annotations actually make the project more beginner-friendly.

I don't think I agree. New developers are going to be following tutorials, reading books and copying chunks from stackoverflow. It is highly likely that these examples will not include type annotations for a while until they catch on. 

We already use asyncio in this project and therefore newbies are forced to use `async` and `await ` syntax, which is already ofputting enough.

> If I get a vote, I'd say "please no typing in docstrings" -- that's mostly a backwards-compatibility thing for Python 2.7, and it makes certain things harder.

Yeah that is fair enough.

> One of the nice things about type annotations and mypy is that it's not an "all-or-nothing" thing.

That is a good point. We are currently doing this with docstrings in #532 to gradually introduce google style docstrings. So we could add these gradually too.

### Overall comment

You make a very compelling argument. I'm just nervous about putting people off.

I'm keen for opsdroid to be a beginner friendly project. I'm also keen for it to teach good practice to new devs. Hence why I am so torn on this issue.

I would be interested to know how @FabioRosado feels given your comment.

**Comment by FabioRosado** [comment]
I still haven't looked into typehints but I'm currently only contributing to opdroid so I never really needed to look much into it. The reason why I thought we should implement a google style docstring with out project was because at times I spent some time trying to figure out what did what and knowing the type and have a good docstring did help.

Is typehinting used with python 3.5? I had a look at mypy and noticed this:

```python
# This is how you declare the type of a variable type in Python 3.6
age: int = 1

# In Python 3.5 and earlier you can use a type comment instead
# (equivalent to the previous definition)
age = 1  # type: int
```

We currently still support python 3.5, will type hinting break our code for this python version?

I still think type hinting look pretty... interesting... and nothing like a person learning python will encounter until type hinting are enforced or used more on other projects,  if I found this statement `x: List[Union[int, str]] = [3, 5, "test", "fun"]` when I was starting with code I would probably run towards the hills and never look back.

I understand the usefulness of this, but also understand how it will make the code more complex for someone that has been learning how to code through tutorials and youtube videos like Jacob has mentioned.

So yeah, I'm a bit torn on this issue as well. It could help in some cases but also make the code harder to read for people that never seen a type hint in their life (I guess we could add a tutorial to help new folks though).

I guess the thing that will decide this issue would be if type hints will break the python 3.5 support and if we want to break support for it at this time?

**Comment by petri** [comment]
As can be seen from the discussion thus far, it's clearly a balancing act - there's valid pros and cons. I would suggest starting to use them at some point in places where they can clearly clarify things, or help avoid errors. Or just start from the key public APIs. Or some mixture of those.

It's also worth remembering that type hints can fall behind and might have bugs (one more reason to start using mypy).
