### ISSUE TITLE
Create a Gitter connector module

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#674]
Let's add a [Gitter connector](https://gitter.im/).

## Steps

 - Make a new submodule directory in [`opsdroid.connector`](https://github.com/opsdroid/opsdroid/tree/master/opsdroid/connector) called `gitter` and create an `__init__.py` file inside.
 - Implement the connector according to the [documentation on writing connectors](https://opsdroid.readthedocs.io/en/stable/extending/connectors/).
 - Update the [`requirements.txt`](https://github.com/opsdroid/opsdroid/blob/master/requirements.txt) with any new dependencies from the connector if necessary.
 - Write tests for the connector. (See the [Slack connector tests](https://github.com/jacobtomlinson/opsdroid/blob/master/tests/test_connector_slack.py) for inspiration).
 - Create a [new documentation page](https://github.com/opsdroid/opsdroid/tree/master/docs/connectors).
 - Add the new page to the [mkdocs.yml](https://github.com/opsdroid/opsdroid/blob/master/mkdocs.yml).
 - Add to the [list of connectors](https://github.com/opsdroid/opsdroid/blob/master/docs/configuration-reference.md#connector-modules).

### Resources to get you started
   - [Gitter API](https://developer.gitter.im/docs/welcome)

### Asyncio
 Opsdroid uses [asyncio and an event loop](https://docs.python.org/3/library/asyncio.html), so here are some things to bear in mind:
   - Functions should be coroutines which are defined with `async def myfunc(): ...`
   - Coroutines are called with `await`. For example `await myfunc()`. This is how asyncio allows many functions to take it in turns as they swap over when the current thread calls `await`.
   - **Don't block the thread!** If you need to make a call to a blocking function such as `time.sleep()` or any kind of IO request such as `requests.get()` then you should `await` an async variant. For example  you can call `await asyncio.sleep(10)` to sleep without blocking the whole application and you can use `aiohttp` as an async url library.

**Comment by moulikcipherX** [comment]
I want to work on this issue...

**Comment by jacobtomlinson** [comment]
@moulikcipherX please go ahead

**Comment by jacobtomlinson** [comment]
Hey @moulikcipherX I'm guessing you've not had time to work on this. If anyone else wants to take this up then please go ahead.

**Comment by varadgunjal** [comment]
I'd like to take this up. Will post updates soon.

**Comment by FabioRosado** [comment]
@varadgunjal  that would be great, please let us know if you need any help with this task 👍

**Comment by Razi007** [comment]
I would like to take this up.If it is still open.

**Comment by FabioRosado** [comment]
Yeah this issue is still open and that would be great 👍 let us know if you need any help

**Comment by Razi007** [comment]
After reading gutter api docs.Here is my plan 

- * set **auth_token** and room info in config file.
- * **listener**: keep listing from room using **gitter stream api’s**.
- * **respond**:respond back skill parsed message via **gitter post api**.

**Comment by FabioRosado** [comment]
Yeah that's basically it, you can have a look at the telegram or rocket.chat connectors since I used the API to connect to these services. That should give you a good guide on what sort of things you might need to implement on the connector.

Also if you struggle with testing, have a look at the tests created for these connectors I'm sure you can implement the same solutions for gitter 😄 👍

**Comment by Razi007** [comment]
@FabioRosado 
Please suggest:

- As gitter uses HTTP stream which keeps connection alive forever.Is it a good approach to keep connection alive and keep listening response from it.
- Does aiohttp.ClientSession() have Http stream support.
- Gitter also have  pooling api's which needs last read message offset.But I think we should use HTTP stream here.

**Comment by FabioRosado** [comment]
Hello Razi apologies for not being able to reply to you earlier.

I agree with you, using the http stream might be the best way to do things since you don't have to keep calling the API every x seconds like we are doing with rocketchat and gitter. Testing this method might take a bit of trial and error since we don't have any tests like this before but should be okay (basically you could set a result with an EOF so the loop finishes)

I checked aiohttp docs and they have http stream support, you can check the [official aiohttp documentation](https://docs.aiohttp.org/en/stable/streams.html). Also if you are unsure how to do it, look at how the ruby/node examples implement the stream logic on the [gitter streaming docs](https://developer.gitter.im/docs/streaming-api)

So you can tackle this issue by created the needed method (connect, listen, respond, disconnect)

And then you might need to add some helper method such as parse message, this will help you while testing the loop in `listen`.

The listen method would be the one using that `aiohttp.StreamReader`, the connect could just call the api and check if everything is fine (like what we do in rocketchat and telegram).

Hope this helps 😄

**Comment by Razi007** [comment]
@FabioRosado 
I want to test connector on my local machine.
using docker to build opsdroid.
```
sudo docker build opsdroid/
docker run image-id
```
but when typing something in gitter unable to get anything.Also if i left some bug in code docker is running fine.If I am doing something wrong?

**Comment by FabioRosado** [comment]
I am unable to help you with this since I don't use docker, perhaps @jacobtomlinson has any idea how to do it 🤔

**Comment by Razi007** [comment]
Okey any suggestion how should i test it.

**Comment by FabioRosado** [comment]
How I usually do it is not TDD but I write the code, test it on the chat service to see if a simple skill is working (like hello) if opsdroid replies all is good. If it doesn't then I try to figure out why.

Make sure you have logging set to debug and console set to true on your `config.yaml` and do step by step.
First check if opsdroid is able to connect to the service (that's why we log that message on the `connect` method), then try to send a message to the chat service and check if opsdroid can read that message, if yes then opsdroid is able to see the messages from that room/chat service.  The last step would be to parse that message and reply.

Writing tests you can check the other connectors and use the same logic. We just need to figure out how to test for aiohttp streams. If you want you can open a PR already and show us the code and we can try and help you from there as well 👍

**Comment by Razi007** [comment]
```
  async def connect(self):
    # Create connection object with chat library
    _LOGGER.debug("Connecting with gitter stream")
    self.session = aiohttp.ClientSession()
    self.response = await self.session.get("https://stream.gitter.im/v1/rooms/:roomId/chatMessages?access_token=:token")

  async def listen(self):
    _LOGGER.debug("Listening with gitter stream")
    while True:
      _LOGGER.debug("into loop")
      await self.parse_response()

  async def parse_response(self):
    content = self.response.content.read()
    
```
@FabioRosado  this is my idea of implementing connector and listener.You can suggest if i am going in right direction.As of now i am getting some errors in parse_response(),Trying to solve it.Will open initial level PR then.Also what is the frequency of calling listener function is it configurable or depends or run by asyncio only.

**Comment by FabioRosado** [comment]
That is up to you, but for you to change the frequency of the call you will have to add a `asyncio.sleep()` after the `await self.parse_response()` what I am doing on rocketchat is using 1second wait before calling the API again, I'd say go with a minimum of 1 second between calls otherwise you will just flood the service and might bring problems haha

**Comment by jacobtomlinson** [comment]
I also recommend adding a `listening` attribute to your connector which defaults to `True` and is set to `False` in the disconnect method. Then use that attribute in your `while` loop, this way the connector will gracefull close when opsdroid is stopping.

**Comment by Razi007** [comment]
@FabioRosado @jacobtomlinson help needed here
just open a [ PR](https://github.com/opsdroid/opsdroid/pull/957/files).
Here I am able to connect with gitter stream.And able to receive message.But when I try to parse message getting en error.Mentioning the same in current pr for better clarification.Also,please suggest if I am missing something .

**Comment by Razi007** [comment]
config file changes::
`## Connector modules

connectors:
  - name: gitter
    bot-name: "mr.boot" # default "opsdroid"
    room-id: "to be added"
    access-token: "to be added"

parsers:
  - name: regex
    enabled: true

skills:
  - name: dance
  - name: hello
  - name: loudnoises
  - name: seen
`
