### ISSUE TITLE
Refactor connector opsdroid pointer

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#725]
Currently in the `Connector` class we expect opsdroid to pass a pointer to itself on `connect` and `disconnect`. This seems a little pointless as the connector should be storing the pointer as an attribute anyway.

### Steps

- Add `opsdroid` as a kwarg in the `__init__` method of the `Connector` class and store it as an attribute. 
- Remove the opsdroid kwarg from the `connect` and `disconnect` method as they are no longer needed.
- All core connectors would also need updating to reflect this.

**Comment by zonagilreath** [comment]
I think I can get this done pretty quickly

**Comment by zonagilreath** [comment]
I will try to work on this.

**Comment by zonagilreath** [comment]
This would be my first contribution to a project so I'm a little unsure of the protocol, should I also update the connector tests to reflect this change?

**Comment by FabioRosado** [comment]
Hello @zonagilreath welcome to the project!
You are correct, the tests will need to be updated as well otherwise they will fail as they will have opsdroid as a param.

Let us know if you need any help 👍

**Comment by FabioRosado** [comment]
Might be a good idea to add the opsdroid kwarg to the database class as well - this is related to the bug report of @colonelkrud 
```python
colonelkrud INFO opsdroid.core: Received stop signal, exiting. INFO opsdroid.core: Removing skills... INFO opsdroid.core: Stopping database ... ERROR opsdroid.core: Caught exception ERROR opsdroid.core: {'message': 'Task exception was never retrieved', 'exception': TypeError('disconnect() takes 1 positional argument but 2 were given',), 'future': <Task finished coro=<OpsDroid.handle_signal() done, defined at /usr/local/lib/python3.6/dist-packages/opsdroid/core.py:120> exception=TypeError('disconnect() takes 1 positional argument but 2 were given',)>}
```

**Comment by jacobtomlinson** [comment]
Yes!

**Comment by zonagilreath** [comment]
Sounds good, I'll checkout the db class once I get the connector tests fixed.

**Comment by zonagilreath** [comment]
I do have a question about the tests. In `test_connector_facebook`, line 34, there's: 
`opsdroid = amock.CoroutineMock()` 
which is later given to `connector.connect(opsdroid)`. 
Later in the same test we have: 
```
with OpsDroid() as opsdroid:
    connector.opsdroid = opsdroid
    connector.opsdroid.parse = amock.CoroutineMock()
```
Keeping this same form shouldn't be an issue with the fb, rocketchat, etc connector tests,  but there's no precedent in just `test_connector` (because the `connect` method isn't implemented in the base class, so isn't tested, and the `__init__` method didn't require the opsdroid arg previously) so is there any advice on whether I should call `OpsDroid` or `CouroutineMock` for the opsdroid kwarg in testing `Connector.__init__`?

**Comment by zonagilreath** [comment]
Oh also, since the issue said "Add opsdroid as a **kwarg**" I'm adding it specifically as a kwarg and it won't be possible to supply it positionally. Is this what is desired?
