### ISSUE TITLE
shell connector fails on start

### ISSUE THREAD

**Issue by petri** [opsdroid/opsdroid#761]
# Description

Installing version 0.13.0 on MacOS, Python 3.6, when trying to use the shell connector, errors occur.

## Steps to Reproduce

Use the barebones configuration with just `shell` connector and `hello` skill. Try starting opsdroid.

## Experienced Functionality

```
  File "/Users/petri/Library/Application Support/opsdroid/opsdroid-modules/connector/shell/__init__.py", line 20, in __init__
    super().__init__(config, opsdroid=opsdroid)
TypeError: __init__() got an unexpected keyword argument 'opsdroid'
```

Don't know if the call or the base class signature should be changed? 

Also, FYI there are some more bugs lurking beneath, try running again after fixing this...

**Comment by FabioRosado** [comment]
Hello @petri thank you for raising this issue. I made changes to the shell connector in order to get #749 merged. But there were a few things still in need to change. I tried to raise a PR within @zonagilreath repo in order to get the tests passing again, but didn't get any reply from him.

I got some time today and will revert the changes done to the shell connector and it should work for you after that 😄 👍
