### ISSUE TITLE
Regex.group broke after events got merged into core

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#934]
# Description
After the events PR was merged to Core an `AttributeError` exception is raised when we try to get a regex group.

The issue stars in `opsdroid.core` on [line 467](https://github.com/opsdroid/opsdroid/blob/d1d25927107892008f62e6bf83d4f82fb994736c/opsdroid/core.py#L467)

And possibly something in `opsdroid.events` is not parsing the regex groups.

## Steps to Reproduce
Have a skill that tries to get a regex group from a sentence.

## Expected Functionality
Opsdroid should be able to use that group in the reply.

## Experienced Functionality
An `AttributeError` exception is raised

_Note: This is a very broad issue. I'll be more than happy to dig deeper into it if needed._

**Comment by jacobtomlinson** [comment]
Does the event have the `regex` property at all?

**Comment by FabioRosado** [comment]
I am going to assume tht it might be something related to how the message is being parsed. Before the events that line was `ranked_skills[0]["message"]` so I guess the Message class is just calling the parsers but not any of the specific methods of that parser? 🤔

**Comment by anxodio** [comment]
I was just about writing and issue about this!

Version 0.15 brokes regex (and parseformat, but let's focus on regex), and I discovered the reason.

In `parse_regex`, regex makes a copy of the Message object instead of directly mutating it:

```python
new_message = copy.copy(message)
new_message.regex = regex
matched_skills.append({
    "score": await calculate_score(
        opts["expression"], opts["score_factor"]),
    "skill": skill,
    "config": skill.config,
    "message": new_message
})
```

Other parsers like the NLU ones directly mutates the original message.

The problem is that Opsdroid ignores the `message` key of the `matched_skills`, as you can see in `core.py -> parse`:

```python
tasks.append(
    self.eventloop.create_task(
        self.run_skill(ranked_skills[0]["skill"],
                       ranked_skills[0]["config"],
                       event)))
```

As you can see, it runs the skill with the original event and ignores the `message` key of the ranked_skills where regex put the new message.

An easy and fast fix is to mutate the original message as before, but I think that we need to think how to redisign this part to avoid that kind of mutations :thinking:

**Comment by jacobtomlinson** [comment]
My suggestion here would be to mutate the original message.

As raised in #933 I'm keen to move from mutating attributes like `message.regex` to adding to a static  dictionary attribute like `message.raw_parses['regex']`.
